version: '3'

services:
  frontend:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    # If you need to connect to a backend service in the same docker network
    # networks:
    #   - app-network

# If you need to define a network for connecting to a backend service
# networks:
#   app-network:
#     external: true  # If the network is created by another docker-compose file 